STATIC_RESPONSES = {
    "google meat": "🍖🥩https://meet.google.com/dof-drim-for 🥩🍖",
    "lets meat": "🍖🥩https://meet.google.com/dof-drim-for 🥩🍖",
    "let's meat": "🍖🥩https://meet.google.com/dof-drim-for 🥩🍖",
    "meating time": "🍖🥩https://meet.google.com/dof-drim-for 🥩🍖",
    "time to meat": "🍖🥩https://meet.google.com/dof-drim-for 🥩🍖",
    "SR-71": ":airplane_departure::speech_balloon: :rabbit2::question:\n:japanese_castle::speech_balloon: :turtle:\n:helicopter::speech_balloon: :rabbit2::question:\n:japanese_castle::speech_balloon: :steam_locomotive:\n⚓️:speech_balloon: :rabbit2::question:\n:japanese_castle::speech_balloon: :bullettrain_side:\n⚓️:speech_balloon: :sunglasses:\n:airplane::speech_balloon: :rabbit2::question:\n:japanese_castle::speech_balloon: :rocket:\n:airplane::speech_balloon: :point_right: :stars:\n:japanese_castle::speech_balloon: :thumbsup: :clap::clap::clap::clap:\n:airplane::speech_balloon: :clap::clap::clap::clap:\n",
    "sr-71": ":airplane_departure::speech_balloon: :rabbit2::question:\n:japanese_castle::speech_balloon: :turtle:\n:helicopter::speech_balloon: :rabbit2::question:\n:japanese_castle::speech_balloon: :steam_locomotive:\n⚓️:speech_balloon: :rabbit2::question:\n:japanese_castle::speech_balloon: :bullettrain_side:\n⚓️:speech_balloon: :sunglasses:\n:airplane::speech_balloon: :rabbit2::question:\n:japanese_castle::speech_balloon: :rocket:\n:airplane::speech_balloon: :point_right: :stars:\n:japanese_castle::speech_balloon: :thumbsup: :clap::clap::clap::clap:\n:airplane::speech_balloon: :clap::clap::clap::clap:\n",
    "never give up": ":fist: https://youtu.be/tYzMYcUty6s",
    "GM zoom": "https://rit.zoom.us/my/aho4817",
    "dat boi": "o shit waddup! :datboi:",
    "brickworks zoom": "https://rit.zoom.us/j/3742506622?pwd=MDdMS0NYTGtzRjhERVFJSUVteUdNQT09",
    "robust": "_r o b u s t_ :open_hands:",
    "inflatable duck": "https://i.pinimg.com/originals/b9/5a/85/b95a855ab0477a672b1c7ee091da0a3c.jpg",
    "duck scale": "https://i.pinimg.com/originals/b9/5a/85/b95a855ab0477a672b1c7ee091da0a3c.jpg",
    "ayooo": ":airhorn: https://youtu.be/UaUa_0qPPgc :airhorn:",
    "taps": ":rip: https://www.youtube.com/watch?v=-IEaWUPisZA :rip:",
    "taps recorder": ":rip: https://www.youtube.com/watch?v=-IEaWUPisZA :rip:",
    "rip in peace": ":rip: https://www.youtube.com/watch?v=-IEaWUPisZA :rip:",
    "off the record": "https://drive.google.com/file/d/1VtAbGPuEKi_6fxYRdIK9rAvsxX1jI_J5/view?usp=sharing",
    "money printer": "brrrr :printer:",
    "of salt": ":salt::salt::salt::salt::salt::salt::salt::salt::salt::salt:",
    "big chungus": "https://cdn.discordapp.com/attachments/918592541354500156/937061690221166623/unknown.png",
    "google meet": "https://meet.google.com/dof-drim-for",
    "Google meet": "https://meet.google.com/dof-drim-for",
    "Google Meet": "https://meet.google.com/dof-drim-for",
    "google Hangouts": "https://meet.google.com/dof-drim-for",
    "google hangouts": "https://meet.google.com/dof-drim-for",
    "Google hangouts": "https://meet.google.com/dof-drim-for",
    "Google Hangouts": "https://meet.google.com/dof-drim-for",
    "hangouts link": "https://meet.google.com/dof-drim-for",
    "Hangouts link": "https://meet.google.com/dof-drim-for",
    "hangouts Link": "https://meet.google.com/dof-drim-for",
    "Hangouts Link": "https://meet.google.com/dof-drim-for",
    "test": "testing testing 123"
}