STATIC_RESPONSES = {
    "google meat": "🍖🥩https://meet.google.com/dof-drim-for 🥩🍖",
    "SR-71": ":airplane_departure::speech_balloon: :rabbit2::question:\n:japanese_castle::speech_balloon: :turtle:\n:helicopter::speech_balloon: :rabbit2::question:\n:japanese_castle::speech_balloon: :steam_locomotive:\n⚓️:speech_balloon: :rabbit2::question:\n:japanese_castle::speech_balloon: :bullettrain_side:\n⚓️:speech_balloon: :sunglasses:\n:airplane::speech_balloon: :rabbit2::question:\n:japanese_castle::speech_balloon: :rocket:\n:airplane::speech_balloon: :point_right: :stars:\n:japanese_castle::speech_balloon: :thumbsup: :clap::clap::clap::clap:\n:airplane::speech_balloon: :clap::clap::clap::clap:\n",
    "sr-71": ":airplane_departure::speech_balloon: :rabbit2::question:\n:japanese_castle::speech_balloon: :turtle:\n:helicopter::speech_balloon: :rabbit2::question:\n:japanese_castle::speech_balloon: :steam_locomotive:\n⚓️:speech_balloon: :rabbit2::question:\n:japanese_castle::speech_balloon: :bullettrain_side:\n⚓️:speech_balloon: :sunglasses:\n:airplane::speech_balloon: :rabbit2::question:\n:japanese_castle::speech_balloon: :rocket:\n:airplane::speech_balloon: :point_right: :stars:\n:japanese_castle::speech_balloon: :thumbsup: :clap::clap::clap::clap:\n:airplane::speech_balloon: :clap::clap::clap::clap:\n",
    "never give up": ":fist: https://youtu.be/tYzMYcUty6s",
    "test": "testing testing 123",
    "iso8601": ":sweat_drops::sweat_drops::sweat_drops::sweat_drops::heavy_minus_sign::white_frowning_face::white_frowning_face::heavy_minus_sign::fire::fire::tea::+1::+1::link::grimacing::grimacing::link::ghost::ghost::zzz:",
    "ISO 8601": ":sweat_drops::sweat_drops::sweat_drops::sweat_drops::heavy_minus_sign::white_frowning_face::white_frowning_face::heavy_minus_sign::fire::fire::tea::+1::+1::link::grimacing::grimacing::link::ghost::ghost::zzz:",
    "Kill me": "https://imgur.com/a/ZWLHmfX",
    "Im dead": "https://imgur.com/a/ZWLHmfX",
    "i'm dead": "https://imgur.com/a/ZWLHmfX",
    "I'm dead": "https://imgur.com/a/ZWLHmfX",
    "kill me": "https://imgur.com/a/ZWLHmfX",
    "im dead": "https://imgur.com/a/ZWLHmfX",
    "launch schedule": "https://www.launchlibrary.net/",
    "when is the next launch": "https://www.launchlibrary.net/",
    "happy birthday": "https://i.imgur.com/47jzfqk.png",
    "loops": "https://i.imgur.com/L09ADWa.jpg",
    "stallman": "https://youtu.be/I25UeVXrEHQ?t=113",
    "want pdd": "https://i.imgflip.com/2d6ydr.jpg",
    "make a pdd": "https://i.imgflip.com/2d6ydr.jpg",
    "need a pdd": "https://i.imgflip.com/2d6ydr.jpg",
    "list of space startups": "https://docs.google.com/spreadsheets/d/1SB9k-eZdDjWub1Bo2y_XfWgRcAQMcATFV1MOGjyFEec/edit#gid=0",
    "i need a new job": "https://docs.google.com/spreadsheets/d/1SB9k-eZdDjWub1Bo2y_XfWgRcAQMcATFV1MOGjyFEec/edit#gid=0",
    "list of space companies": "https://docs.google.com/spreadsheets/d/1SB9k-eZdDjWub1Bo2y_XfWgRcAQMcATFV1MOGjyFEec/edit#gid=0",
    "company list": "https://docs.google.com/spreadsheets/d/1SB9k-eZdDjWub1Bo2y_XfWgRcAQMcATFV1MOGjyFEec/edit#gid=0",
    "list of companies": "https://docs.google.com/spreadsheets/d/1SB9k-eZdDjWub1Bo2y_XfWgRcAQMcATFV1MOGjyFEec/edit#gid=0",
    "space company list": "https://docs.google.com/spreadsheets/d/1SB9k-eZdDjWub1Bo2y_XfWgRcAQMcATFV1MOGjyFEec/edit#gid=0",
    "what issue here is": ":fil: :philnamethis: :fil:",
    "i s s u e": ":fil: :philnamethis: :fil:",
    "w h a t i s t h e i s s u e h e r e": ":fil: :philnamethis: :fil:",
    "what's the issue here": ":fil: :philnamethis: :fil:",
    "what is the issue here": ":fil: :philnamethis: :fil:",
    "whats the issue here": ":fil: :philnamethis: :fil:",
    "horse": ":thehorse:",
    "spacex launch you up": "https://www.youtube.com/watch?v=NY7N02eZGoQ",
    "erect": "https://twitter.com/elonmusk/status/949075475036487680",
    "where u at plants": ":seedling::eyes:",
    "wuap": ":seedling::eyes:",
    "momentum is pretty cool": ":ee:",
    "courtesy of phil": ":phil:",
    "project definition document": ":fil: https://github.com/RIT-Space-Exploration/SPEX-Standard-Proposal/ :fil:",
    "project proposal document": ":fil: https://github.com/RIT-Space-Exploration/SPEX-Standard-Proposal/ :fil:",
    "elon musk": "http://i.imgur.com/rWL04wr.gifv",
    "wat": "http://i.imgur.com/qsinY1s.jpg",
    "space is hard": "https://media.giphy.com/media/M8IJSVtPP6yxq/giphy.gif",
    "spex logo": "https://drive.google.com/a/g.rit.edu/file/d/1F30OZDNoWUsEMZclFdg1AA3HTkuU9hYH/view?usp=sharing",
}